on:
  schedule:
    - cron: '0 4 25 * *'   # Runs at 04:00 UTC on the 25th of the month
  workflow_dispatch:
    inputs:
      commit_new_json:
        type: boolean
        description: |
          Commit and push the zulip JSON back to the repo.
          (Note: doing this too often will overload GitHub, doing it too infrequently will overload Zulip)
        required: true
        default: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish_archive_job:
    runs-on: ubuntu-latest
    name: A job to publish zulip-archive in GitHub pages
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Run archive
      id: archive
      uses: eric-wieser/zulip-archive/compound@better-action
      with:
        zulip_organization_url: ${{ secrets.zulip_organization_url }}
        zulip_bot_email: ${{ secrets.zulip_bot_email }}
        zulip_bot_key: ${{ secrets.zulip_bot_key }}
        commit_new_json: ${{ github.event_name == 'schedule' || inputs.commit_new_json }}

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c # v1.2.1
