on:
  workflow_dispatch:
    inputs:
      commit_new_json:
        type: boolean
        description: |
          Whether to commit and push the zulip JSON back to the repo.
          Doing this too often will overload GitHub, doing it to infrequently will overload Zulip.
        required: true
        default: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish_archive_job:
    runs-on: ubuntu-latest
    name: A job to publish zulip-archive in GitHub pages
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run archive
      id: archive
      uses: eric-wieser/zulip-archive/compound@better-action
      with:
        zulip_organization_url: ${{ secrets.zulip_organization_url }}
        zulip_bot_email: ${{ secrets.zulip_bot_email }}
        zulip_bot_key: ${{ secrets.zulip_bot_key }}
        commit_new_json: ${{ inputs.commit_new_json }}
